@BASE_URL=http://localhost:5000/api/v1

### Health Check
GET {{BASE_URL}}/health
Accept: application/json
Content-Type: application/json

### Test Connection
POST {{BASE_URL}}/db/test-connection
Accept: application/json
Content-Type: application/json

{
    "dbUrl": "postgresql://postgres:d02ev@localhost:5432/gen_schema_db"
}

### Get Schemas
GET {{BASE_URL}}/db/get-schemas?dbUrl=postgresql://postgres:d02ev@localhost:5432/gen_schema_db
Accept: application/json
Content-Type: application/json

### Get Tables
GET {{BASE_URL}}/db/get-tables?dbUrl=postgresql://postgres:d02ev@localhost:5432/gen_schema_db&tableSchema=public
Accept: application/json
Content-Type: application/json

### Get Diagram Data
GET {{BASE_URL}}/db/get-diagram-data?dbUrl=postgresql://postgres:d02ev@localhost:5432/gen_schema_db&tableSchema=public&tableNames=users,user_profiles,user_documents
Accept: application/json
Content-Type: application/json